<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://rgqancy.yuanchuangyun.com" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://rgqancy.yuanchuangyun.com" xmlns:intf="http://rgqancy.yuanchuangyun.com" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://rgqancy.yuanchuangyun.com" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="HelloWorld">
    <complexType/>
   </element>
   <element name="HelloWorldResponse">
    <complexType>
     <sequence>
      <element name="HelloWorldReturn" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="HelloWorldRequest">

      <wsdl:part element="impl:HelloWorld" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="HelloWorldResponse">

      <wsdl:part element="impl:HelloWorldResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="testWebService">

      <wsdl:operation name="HelloWorld">

         <wsdl:input message="impl:HelloWorldRequest" name="HelloWorldRequest">

       </wsdl:input>

         <wsdl:output message="impl:HelloWorldResponse" name="HelloWorldResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="testWebServiceSoapBinding" type="impl:testWebService">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="HelloWorld">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="HelloWorldRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="HelloWorldResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="testWebServiceService">

      <wsdl:port binding="impl:testWebServiceSoapBinding" name="testWebService">

         <wsdlsoap:address location="http://localhost/WebServiceWithOSS/services/testWebService"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
